name: sign
main: com.i5mc.sign.Main
version: ${project.version}

commands:
  sign:
    aliases: ['签到','每日签到']
    description: None.
    permission: signin.use

permissions:
  signin.use:
    description: None.
    default: true

depend: [SimpleORM, PlaceholderAPI]
